/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author anthony.ricse
 */
public class vistaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form vistaCalculadora
     */
    public vistaCalculadora() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panLienzo = new java.awt.Panel();
        panButtons = new java.awt.Panel();
        btnC = new javax.swing.JButton();
        btnRadicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnElevar = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 500));

        panLienzo.setLayout(new java.awt.GridBagLayout());

        panButtons.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panButtons.setLayout(new java.awt.GridLayout(5, 4));

        btnC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnC.setText("C");
        panButtons.add(btnC);

        btnRadicar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRadicar.setText("√");
        btnRadicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadicarActionPerformed(evt);
            }
        });
        panButtons.add(btnRadicar);

        btnDividir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDividir.setText("/");
        panButtons.add(btnDividir);

        btnCE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCE.setText("CE");
        panButtons.add(btnCE);

        btn7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn7.setText("7");
        panButtons.add(btn7);

        btn8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn8.setText("8");
        panButtons.add(btn8);

        btn9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn9.setText("9");
        panButtons.add(btn9);

        btnMultiplicar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMultiplicar.setText("x");
        panButtons.add(btnMultiplicar);

        btn4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn4.setText("4");
        panButtons.add(btn4);

        btn5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn5.setText("5");
        panButtons.add(btn5);

        btn6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn6.setText("6");
        panButtons.add(btn6);

        btnRestar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRestar.setText("-");
        panButtons.add(btnRestar);

        btn1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn1.setText("1");
        panButtons.add(btn1);

        btn2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn2.setText("2");
        panButtons.add(btn2);

        btn3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panButtons.add(btn3);

        btnSumar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSumar.setText("+");
        panButtons.add(btnSumar);

        btnElevar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnElevar.setText("^");
        panButtons.add(btnElevar);

        btn0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn0.setText("0");
        panButtons.add(btn0);

        btnPunto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPunto.setText("3.14");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        panButtons.add(btnPunto);

        btnResultado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResultado.setText("=");
        panButtons.add(btnResultado);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Prueba y Validación (TDD)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panLienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panLienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnRadicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRadicarActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuntoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn0;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    public javax.swing.JButton btnC;
    public javax.swing.JButton btnCE;
    public javax.swing.JButton btnDividir;
    public javax.swing.JButton btnElevar;
    public javax.swing.JButton btnMultiplicar;
    public javax.swing.JButton btnPunto;
    public javax.swing.JButton btnRadicar;
    public javax.swing.JButton btnRestar;
    public javax.swing.JButton btnResultado;
    public javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Panel panButtons;
    private java.awt.Panel panLienzo;
    // End of variables declaration//GEN-END:variables
}
